# Generated by Django 3.1.4 on 2020-12-27 07:43

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import markdownx.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('in_development', 'in_development'), ('deployed', 'deployed')], default='in_development', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=60)),
                ('description', markdownx.models.MarkdownxField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'])),
                ('featured', models.BooleanField(default=False)),
                ('what_ive_learned', markdownx.models.MarkdownxField()),
                ('github_link', models.URLField(blank=True, verbose_name='Github repository link')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('web_link', models.URLField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('carousel', models.ManyToManyField(blank=True, to='core.Thumbnail')),
                ('tech_stack', models.ManyToManyField(to='projects.Technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
