# Generated by Django 3.1 on 2020-08-20 16:27

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import markdownx.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('in_development', 'in_development'), ('deployed', 'deployed')], default='in_development', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('is_removed', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'])),
                ('tech_stack', models.CharField(choices=[('django_vuejs', 'django_vuejs'), ('django', 'django'), ('vuejs', 'vuejs'), ('wagtail', 'wagtail'), ('wagtail_vuejs', 'wagtail_vuejs')], default='django', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('what_ive_learned', markdownx.models.MarkdownxField(blank=True, verbose_name="What I've learned")),
                ('github_link', models.URLField(blank=True, verbose_name='Github repository link')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('web_link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
