# Generated by Django 3.1 on 2020-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(choices=[('django_vuejs_html_css_bootstrap4', 'django_vuejs_html_css_bootstrap4'), ('django_vuejs_html_css_bulma', 'django_vuejs_html_css_bulma'), ('django_html_css_bootstrap4', 'django_html_css_bootstrap4'), ('django_html_css_bulma', 'django_html_css_bulma'), ('vuejs_html_css_bootstrap4', 'vuejs_html_css_bootstrap4'), ('vuejs_html_css_bulma', 'vuejs_html_css_bulma'), ('wagtail_html_css_bootstrap4', 'wagtail_html_css_bootstrap4'), ('wagtail_html_css_vuejs', 'wagtail_html_css_vuejs')], default='django_vuejs_html_css_bootstrap4', max_length=100),
        ),
    ]
