# Generated by Django 3.0.5 on 2020-06-23 18:01

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='in_development', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
