# Generated by Django 3.1 on 2020-08-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenance'),
        ('projects', '0002_auto_20200828_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='carousel',
            field=models.ManyToManyField(blank=True, null=True, to='core.Thumbnail'),
        ),
    ]
