# Generated by Django 3.0.5 on 2020-06-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200623_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uuid',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
