# Generated by Django 3.1 on 2020-08-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenance'),
        ('projects', '0003_auto_20200829_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='carousel',
            field=models.ManyToManyField(blank=True, to='core.Thumbnail'),
        ),
    ]
