# Generated by Django 3.0.5 on 2020-06-23 19:42

from django.db import migrations, models
import django_extensions.db.fields
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200623_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, verbose_name='Github repository link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title']),
        ),
        migrations.AlterField(
            model_name='project',
            name='what_ive_learned',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name="What I've learned"),
        ),
    ]
