# Generated by Django 3.0.5 on 2020-06-23 20:35

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200623_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='full_name'),
        ),
    ]
