# Generated by Django 3.1.1 on 2020-09-24 20:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200829_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='what_ive_learned',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
