# Generated by Django 3.0.5 on 2020-06-24 20:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_collaborator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default='DEGNON Tobi', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status'),
        ),
    ]
