# Generated by Django 3.0.5 on 2020-07-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200624_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(choices=[('django_vue', 'django_vue'), ('django', 'django'), ('vue', 'vue')], default='django', max_length=15),
        ),
    ]
