# Generated by Django 3.1 on 2020-08-25 11:02

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200820_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='thumbnails')),
                ('source', models.URLField(blank=True, null=True)),
                ('alt', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['alt'])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
