# Generated by Django 3.1 on 2020-08-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedIn_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
