# Generated by Django 3.1 on 2020-08-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200826_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
