# Generated by Django 3.1.1 on 2020-09-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
