# Generated by Django 3.1.1 on 2020-10-06 10:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_thumbnail_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('maintenance_state', models.BooleanField(default=False)),
                ('code_theme', models.CharField(choices=[('monokai', 'monokai'), ('default', 'default'), ('perldoc', 'perldoc')], default='monokai', max_length=10)),
                ('phone_number', models.CharField(default='+22963588213', max_length=12)),
                ('github', models.URLField(default='https://github.com/Tobi-De')),
                ('telegram', models.URLField(default='https://t.me/Tobi_DE1999')),
                ('twitter', models.URLField(default='https://twitter.com/Tobi71110248?ref_src=twsrc%5Etfw')),
                ('linkedIn', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
