# Generated by Django 3.1 on 2020-08-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
