# Generated by Django 3.1 on 2020-08-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscriptionreason',
            name='email',
            field=models.EmailField(default='degnonfrancis@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
