# Generated by Django 3.1.1 on 2020-09-24 20:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='message',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
