# Generated by Django 3.1 on 2020-08-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_unsubscriptionreason_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnsubscriptionReason',
        ),
    ]
