# Generated by Django 3.1 on 2020-08-23 08:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200822_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
