# Generated by Django 3.0.5 on 2020-07-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='submissions',
            field=models.ManyToManyField(to='newsletter.Submission'),
        ),
    ]
