# Generated by Django 3.1 on 2020-08-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20200823_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dispatch_date',
            field=models.DateTimeField(),
        ),
    ]
