# Generated by Django 3.0.5 on 2020-07-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='submissions',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='users',
        ),
        migrations.AddField(
            model_name='submission',
            name='newsletter',
            field=models.ManyToManyField(to='newsletter.Newsletter'),
        ),
    ]
