# Generated by Django 3.1 on 2020-08-23 19:13

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20200823_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='key_identifer',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32),
        ),
    ]
