# Generated by Django 3.0.5 on 2020-07-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20200714_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='verified',
            new_name='confirmed',
        ),
    ]
