# Generated by Django 3.1 on 2020-08-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_news_key_identifer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='key_identifer',
            new_name='key_identifier',
        ),
    ]
