# Generated by Django 3.1.4 on 2020-12-27 07:42

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='thumbnails')),
                ('source', models.URLField(blank=True, null=True)),
                ('alt', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['alt'])),
                ('primary', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('maintenance_state', models.BooleanField(default=False)),
                ('code_theme', models.CharField(choices=[('monokai', 'monokai'), ('default', 'default'), ('perldoc', 'perldoc')], default='monokai', max_length=10)),
                ('phone_number', models.CharField(default='+22963588213', max_length=12)),
                ('github', models.URLField(default='https://github.com/Tobi-De')),
                ('telegram', models.URLField(default='https://t.me/Tobi_DE1999')),
                ('twitter', models.URLField(default='https://twitter.com/Tobi71110248?ref_src=twsrc%5Etfw')),
                ('linkedIn', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ToolBox',
            },
        ),
    ]
