# Generated by Django 3.1 on 2020-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='automatic_publish_mail',
            field=models.BooleanField(default=True),
        ),
    ]
