# Generated by Django 3.0.5 on 2020-06-24 20:29

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200624_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogpostseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogposts', to='blog.BlogPostSeries'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
