# Generated by Django 3.0.5 on 2020-06-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200624_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpostseries',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
