# Generated by Django 3.0.5 on 2020-06-25 11:53

from django.db import migrations, models
import markdownx.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200625_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='blogpostseries',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
