# Generated by Django 3.1.2 on 2020-10-14 18:57

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='secret_key',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=64),
        ),
    ]
