# Generated by Django 3.0.5 on 2020-06-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200628_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
