# Generated by Django 3.1.2 on 2020-10-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reading_time',
        ),
    ]
