# Generated by Django 3.1.2 on 2020-10-19 20:38

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=120, populate_from=['title']),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=120, populate_from=['title']),
        ),
    ]
