# Generated by Django 3.0.5 on 2020-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200707_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='code_review.svg', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogpostseries',
            name='thumbnail',
            field=models.ImageField(default='code_review.svg', upload_to='blog'),
        ),
    ]
