# Generated by Django 3.1.2 on 2020-10-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201024_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
