# Generated by Django 3.0.5 on 2020-07-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200707_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='overview',
            field=models.CharField(default='This is an overview', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostseries',
            name='overview',
            field=models.CharField(default='This is the series overview', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogpostseries',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
