# Generated by Django 3.0.5 on 2020-07-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200710_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='overview',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpostseries',
            name='overview',
            field=models.TextField(max_length=200),
        ),
    ]
