# Generated by Django 3.1.4 on 2020-12-27 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import markdownx.models
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('overview', markdownx.models.MarkdownxField()),
                ('body', markdownx.models.MarkdownxField(blank=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=120, populate_from=['title'])),
                ('status', model_utils.fields.StatusField(choices=[('in_progress', 'in_progress'), ('on_break', 'on_break'), ('finished', 'finished')], default='in_progress', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('visible', models.BooleanField(default=False)),
                ('thumbnail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.thumbnail')),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('overview', markdownx.models.MarkdownxField()),
                ('body', markdownx.models.MarkdownxField(blank=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=120, populate_from=['title'])),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('secret_key', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=64)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.series')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('thumbnail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.thumbnail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
